jumpstart/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from . import views
app_name = 'jumpstart'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('car-not-starting/', views.car_not_starting, name='car-not-starting'),
    path('car-jump-start-service-chicago/', views.dead_battery, name='dead-car-battery'),
    path('thankyou/', views.request_services, name='thankyou'),
    path('sitemap.xml', views.site_map, name='sitemap'),
    path('spanish/', views.spanish_jump_start, name='spanish_jump'),

    path('robots.txt', TemplateView.as_view(template_name="jumpstart/robots.txt", content_type="text/plain"),
         name="robots_file")

]

jumpstartservice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('berenisesilvano/', admin.site.urls),
    path('', include('jumpstart.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jumpstart/models.py
from django.db import models


class Profile(models.Model):
    profile_pic = models.ImageField(upload_to='media', blank=True)

    def __str__(self):
        return self.profile_pic.path

jumpstart/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings


def home_view(request):
    return render(request, 'jumpstart/home.html')


def dead_battery(request):
    return render(request, 'jumpstart/car-jump-start-service-chicago.html')


def spanish_jump_start(request):
    return render(request, 'jumpstart/spanish_jump.html')


def car_not_starting(request):
    return render(request, 'jumpstart/car-not-starting.html')


def site_map(request):
    return render(request, 'jumpstart/sitemap.xml', content_type='text/xml')



def request_services(request):
    get_manual_address = request.POST.get('manual_address')
    phone_number = request.POST.get('phone')
    lengua = request.POST.get('lengua')

    direccion = get_manual_address
    phone_number = ' Phone Number: {}'.format(str(phone_number))
    msg = direccion + phone_number + " : {}".format(lengua)

    email_user = 'silvanovaldez90@yahoo.com'

    send_mail('jumpstartcarservice', 'Bienvenido!', settings.EMAIL_HOST_USER, [email_user], html_message=msg,
              fail_silently=False)
    return render(request, 'jumpstart/thankyou.html', {'lan': 'english', 'total': '60'})

jumpstart/templates/jumpstart/car-not-starting.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap4 %}
<html lang="en">
<head>

    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-135035488-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-135035488-1');
</script>

    <meta name="google-site-verification" content="Xh4b-vbI3iSpApnHIJfn1fABxBZ8kae5X5GhckCk3es" />

    <title>$39 Car Lockout Service Chicago,IL Jumpstartcarservice. Free ETA & Fastest and cheapest in Chicago</title>

    <meta charset="UTF-8" content="width=device-width, initial-scale=1" name="viewport" >
    <meta name="description" content="$39 for a car lockout service in Chicago, IL. Fast and cheap. No call needed. Will be there in 20 minutes or less.">

    <meta name="keywords" content="Jump start car service, car won't start, dead car battery, Jump Start Service Chicago">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}"/>
</head>
<body class="main">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">


    <a class="small_font navbar-brand" href="{% url 'jumpstart:home'%}">Jumpstartcarservice
    </a>


            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbarXs">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="collapsingNavbarXs">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    services
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'jumpstart:dead-car-battery'%}">Chicago jump start service</a>

                    </div>
                </li>



            </ul>
        </div>



</nav>





<div align="center"><h1>Jump start only $39</h1></div>
    <div class="bottom_margin container" align="center">
                            <div style="position: relative; text-align: center; color: white">
                            <div style="margin-top: 5px; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">

                                <h4 style="background-color: black">Car Jump Start Service</h4>
                                <h4 style="background-color: black">Free Estimate</h4>

                            </div>

                            <img style="width: 100%"
                             src="https://chicagocarhelp.s3.us-east-2.amazonaws.com/jumpstart_cables.jpg"
                             alt="car not starting" title="car not starting">
                                <a href="{% url 'jumpstart:home'%}">
                                <button type="button" class="btn btn-primary btn-lg" style="margin: 5px">Click Here To Get Jump Start</button></a>

                        </div>

    </div>

<div class="container">
    <div align="left" style="border: 1px solid blue; padding: 5px; margin: 5px">
        <h4 align="center">Why a car is not starting</h4>
        <h5>Dead battery</h5>
        <p>A dead battery is the most common reason why your car is not starting. The battery is what the car uses to provide electrical power to the entire car and electrical components (e.g. lights, radio, etc.). While the vehicle is running, the alternator charges the battery. If the battery is not charged sufficiently, you will not be able to start the car or use any electrical components.</p>
        <ul>
        <li>Your headlights or dome light was left on overnight or for too long</li>
        <li>You have a loose wire</li>
        <li>The water inside the component evaporated, leading to poor conductivity</li>
        <li>The battery's lifespan has expired</li>
        </ul>
        <h5>Bad Ignition Switch</h5>
        <p>If you know your battery is working properly, but your car doesn’t turn over on the first few tries, you might have a problem with the ignition switch. You can try to narrow down the cause of your issue by turning on your headlights. Because the battery controls your headlights and dashboard, if they turn on, but your engine won’t start, a bad ignition switch is the likely culprit.</p>

        <h5>Broken starter</h5>
        <p>Similar to a bad ignition switch, a broken starter is another common reason your car won’t start. As the name implies, the starter provides the turning force necessary to get everything moving to start the engine. If you hear a clicking noise when you try to start your vehicle, a broken or weakened starter could be to blame.</p>
    </div>
</div>

<div class="container">
    <div align="left" style="border: 1px solid red; margin: 5px; padding: 5px">
        <h4 align="center">How to check what's wrong</h4>
        <h5>Starter goes click?</h5>
        <p>
            If the car clicks when trying to start, but still won’t start, this can be caused by a weak battery,
            dirty battery terminals, a worn starter motor or a stuck solenoid. If your car turns on
            but won’t start, turn on the dome light and watch it while
        you try to start the engine. If the light goes out, it’s a sign the battery is
        really weak—almost dead. To heat up the battery, terminals and starter, try
        the “key cycling” trick. The trick is to turn the key to the start position repeatedly about 10
        times in a row. Stop and wait five minutes. Then try to start the engine. But if the
        dome light stayed bright when you turned the key, move on to the next trick if your car won’t start.
        </p>

        <h5>No click when you turn the key?</h5>
        <p>
            With your foot on the brake, move the shift lever to the neutral position and try starting
            the engine. If that doesn't work, move it back to “Park” and try it again. Moving the shifter
            sometimes reestablishes electrical contact inside the transmission range selector (also known
            as the neutral safety switch).
        </p>
        <h5>Engine cranks but won’t fire up?</h5>
        <p>
            With the radio off, turn the key to the “Run” position and listen for a two-second
            buzzing sound. That’s the fuel pump priming the injection system. If you don’t hear any
            sound, the fuel pump relay may be bad or the pump may be on its last legs. First, find the
            location of the fuel pump relay in your owner’s manual or on the legend of the under-hood
            fuse box cover. Yank the fuel pump relay straight up. Then locate another relay with the
            same part number and swap it with the fuel pump push it straight into the socket. Try starting
            the engine afterward.
        </p>

    </div>
</div>


    <div class="container">
    <h6>More info</h6>
    <a href="https://www.geico.com/more/driving/auto/auto-care/what-to-do-if-your-car-wont-start/">Why a car won't start</a><br>
    <a href="https://www.askmen.com/cars/car_tips_100/105_car_tip.html">How to change a dead car battery</a><br>
    <a href="https://axleaddict.com/auto-repair/Whats-Wrong-With-My-Car-Five-Signs-Youre-Battery-Is-Dead">Signs of a dead car battery</a><br>
    <a href="https://www.chicagocarhelp.com/Jump-Start-Service-Illinois-Chicago/">Jump Start Car Service</a><br>
    <a href="https://www.chicagocarhelp.com/">Battery Jump Start Service Chicago</a><br>
    </div>




    <script src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>

<script>
    function xc() {
        let whole_text = document.getElementById('show-compe').style;
        whole_text.visibility = 'visible';
        whole_text.display = 'block'

    }
    document.getElementById('dis-compe').addEventListener("click", xc, false)

</script>


</body>
</html>

jumpstart/templates/jumpstart/spanish_jump.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap4 %}
<html lang="en">
<head>

    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-135035488-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-135035488-1');
</script>

    <meta name="google-site-verification" content="Xh4b-vbI3iSpApnHIJfn1fABxBZ8kae5X5GhckCk3es" />

    <title>$39 Battery Jump Start Car Service Chicago,IL Jumpstartcarservice. Free ETA & Fastest and cheapest in Chicago</title>

    <meta charset="UTF-8" content="width=device-width, initial-scale=1" name="viewport" >
    <meta name="description" content="$39 for a jump start service. Fast and cheap. No call needed. Will be there in 20 minutes or less.">

    <meta name="keywords" content="Jump start car service, car won't start, dead car battery, Jump Start Service Chicago">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}"/>
</head>
<body class="main">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">


    <a class="small_font navbar-brand" href="{% url 'jumpstart:home'%}">Jumpstartcarservice
    </a>


            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbarXs">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="collapsingNavbarXs">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    services
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'jumpstart:car-not-starting'%}">car not starting?</a>
                                <a class="dropdown-item" href="{% url 'jumpstart:dead-car-battery'%}">Chicago jump start service</a>

                    </div>
                </li>



            </ul>
        </div>



</nav>

    <div class="top_margin container" align="center">


    <div class="card text-white bg-dark mb-3 purple_shadow">
            <div class="card-body">


                                            <div style="position: relative; text-align: center; color: white">


                            <img style="width: 100%"
                             src="https://chicagocarhelp.s3.us-east-2.amazonaws.com/jumpstart_cables.jpg"
                             alt="car jump start service and roadside assistance" title="car jump start service">
                        </div>


                <h5 class="card-text">Le pasamos corriente (pasar cables) a su carro por $25</h5>



            </div>


        <div style="color: white; background-color: black; border-radius: 4px; margin: 0 1px 4px 1px">
            <p>Solo paga si el carro prende, no tienes nada que perder</p>
            <p style="color: #009a00">Ingrese la ubicación / teléfono para un estimado gratis</p>

        </div>


        <form action="{% url 'jumpstart:thankyou'%}" method="post">
                {% csrf_token %}
                <input class="form-control" type="text" name="manual_address" value="" id="add_manual_address"
                       placeholder="Ingresa tu Dirección" style="padding: 3px; border: 1px solid #571746; border-radius: 5px; margin-bottom: 3px">
                <input type='hidden' name="lengua" value="MX" id="lat">
                <p class="small" id="phone_output"></p>
                <label for="phone">


                    <img class="card-img-top"
                         src="https://chicagocarhelp.s3.us-east-2.amazonaws.com/jumpstart_phone.png"
                         alt="tire" style="width: 20px; height: 20px; margin-top: -10px">
                    <input type="text" required name="phone" placeholder="Ingresa número telefónico" id="phone"
                           style="padding: 3px; border: 1px solid #571746; border-radius: 5px; margin-bottom: 3px"></label>
                <button type="submit" class="bottom_margin btn btn-success btn-lg btn-block"
                        id="request">HAGA CLIC AQUÍ AL TERMINAR</button>
                    <h5 style="color: #ffffff">Aceptamos tarjeta de Crédito / Débito, Efectivo o Venmo</h5>



            </form>
                            </div>


                        <a href="tel:+17085489664"><button class="btn btn-info btn-lg">Presione Para Llamar</button></a>
                        <p>708-548-9664</p>





                    <img src="https://chicagocarhelp.s3.us-east-2.amazonaws.com/jumpstart_clock.png" alt="roadside assistance" style="width: 150px; display: block; margin-top: 10px">
        <div align="center" style="border: 2px solid white; margin-top: 5px; padding: 5px; width: 335px; background-color: #29abe2; border-radius: 7px">
            <h5 style="color: white">RAPIDO</h5>
        <h5 style="color: white">Llegaremos en 10 a 20 minutos o menos</h5>
        </div>




        <div class="card" style="width: 18rem; margin: 10px">
            <h5 class="card-title">Pagos</h5>

                <img src="https://chicagocarhelp.s3.us-east-2.amazonaws.com/here903Asset_30.png" alt="free jump start chicago" style="width: 240px">
          <div class="card-body">



          </div>
        </div>




        <div align="center" style="margin-top: 7px; margin-bottom: 15px">
           <iframe class="makevideobig" id="vp1Dp0J6" title="Video Player" width="100%" height="200" frameborder="0" src="https://s3.amazonaws.com/embed.animoto.com/play.html?w=swf/production/vp1&e=1558305867&f=u2SohXLv7Sr78FJZ91Rw0g&d=0&m=a&r=360p&volume=100&start_res=undefined&i=m&asset_domain=s3-p.animoto.com&animoto_domain=animoto.com&options=" allowfullscreen></iframe>

            <div class="card text-dark bg-light mb-3 green_shadow">
              <div class="card-body">
                <p class="card-text make_big" style="margin-top: -10px; font-size: 18px" >Cómo funciona nuestro servicio</p>

              </div>
            </div>


        </div>


            <div align="center">
        <hr style="color: yellow; background-color: yellow">
        <h4>Ubicaciones en Chicago IL</h4>


        <div class="col-lg-12 col-12">

            <div class="row">
                <div class="col-sm">
                    <p>60606, 60607, 60608, 60610, 60611, 60612, 60613, 60614, 60616, 60618, 60622, 60623, 60624, 60302, 60402</p>

                </div>

                <div class="col-sm">
                    <p>60625, 60630, 60638, 60639, 60640, 60641, 60642, 60644, 60647, 60651, 60654, 60657, 60661, 60304, 60804</p>
                </div>

                <div class="col-sm">
                    <p><a href="https://goo.gl/maps/Vtxbudw8kgY3RA2T7">Albany Park</a>, <a href="https://goo.gl/maps/xpyAzsKVsaVxWRab6">Ravenswood</a>,
                        <a href="https://goo.gl/maps/X2Dk8MRrn7VbdTAB6">Uptown</a>, <a href="https://goo.gl/maps/3Ske3qhS6XwPS8vT6">Edgewater</a>,
                        <a href="https://goo.gl/maps/5JdxbeMvqZgLeaaS6">Irvinpark</a>, <a href="https://goo.gl/maps/DoBrYHv6WCG1Mzwo6">Roscoe Village</a>,
                        <a href="https://goo.gl/maps/WCXSuHZ33QMYEDAa9">Boystown</a>, <a href="https://goo.gl/maps/JZ3qbkx9ZH6nMY5y9">Lake View</a>,
                        <a href="https://goo.gl/maps/bXdF3riKpMvJ3qER6">Lincoln Park</a>, <a href="https://goo.gl/maps/A7nJrw4AuZ4M4EA17">Bucktown</a>,
                        <a href="https://goo.gl/maps/QkTurGm8oYVdrSnw8">Logan Square</a>, <a href="https://goo.gl/maps/DthJrcoLmoV7pmV7A">Wicker Park</a>,
                        <a href="https://goo.gl/maps/HERFg1aGmrQ3vYvaA">Hermosa</a>, <a href="https://goo.gl/maps/Wy5vjWV1jDToPiNv6">Humbold Park</a>,
                        <a href="https://goo.gl/maps/MNjBg1ekR9yh8rH5A">Ukrainian Village</a>, <a href="https://goo.gl/maps/wYAipt91MFqMcDEH7">Near North side</a>,
                        <a href="https://goo.gl/maps/36yPPpNETQESxXaW7">River North</a>, <a href="https://goo.gl/maps/GEnthGTtZEnZhSmF6">River West</a>,
                        <a href="https://goo.gl/maps/SwmLyu4jb5QVdW2V6">Near West Side</a>, <a href="https://goo.gl/maps/bK7HwDtWybGvDkMy5">South Loop</a>,
                        <a href="https://goo.gl/maps/i4HY7L2sGtbJAQjS6">Chinatown</a>, <a href="https://goo.gl/maps/q3bNHupUmQ8GtRzY9">Downtown</a>,
                        <a href="https://goo.gl/maps/xZzjVuiTjpzrAyvd9">Homan Square</a>, <a href="https://goo.gl/maps/zjDdwDyhci1dbug58">Little Italy</a>,
                        <a href="https://goo.gl/maps/qx26daJTC3tPcXBv5">Chicago</a>, <a href="https://goo.gl/maps/woi6ADUg7N9E4rp88">Cook County</a>
                    </p>

                </div>
            </div>

         </div>
    </div>






</div>


    <script src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>

<script>
    function xc() {
        let whole_text = document.getElementById('show-compe').style;
        whole_text.visibility = 'visible';
        whole_text.display = 'block'

    }
    document.getElementById('dis-compe').addEventListener("click", xc, false)

</script>


</body>
</html>

jumpstart/templates/jumpstart/thankyou.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load bootstrap4 %}
<head>
    <link rel="canonical" href="https://www.jumpstartcarservice.com/" />
    <title>Thank You</title>
        <meta charset="UTF-8" content="width=device-width, initial-scale=1" name="viewport" >
    <meta name="description" content="Learn why your car is not starting and request a jump start for only $39. Fast and cheap">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}"/>
</head>
<body>


    <img src="https://chicagocarhelp.s3.us-east-2.amazonaws.com/jumpstart_thanks.jpg" alt="" style="width: 100%; height: auto">

    <div align="center">
            <h5 style="color: #0005cc">We accept credit/debit card, cash or Venmo</h5>
            <h5 style="color: #0005cc">You will be charged when your service has been completed</h5>
    </div>
    <div class="container"><h5 class="centered">Thank you for choosing WWW.JUMPSTARTCARSERVICE.COM for your road side assistance. I will contact you in a few minutes.</h5></div>


</body>
</html>